export function getAuthError(e: any) {
    switch (e) {
        default: {
            // TODO: エラー処理
            alert("エラーが発生しました。再度お試しください。")
            console.log(e)
        }
      }
}
